[package]
name = "hrynchuk_email_parser"
version = "0.1.0"
edition = "2021"
description = "An email parser that validates email addresses using grammar rules."
license = "MIT"

[dependencies]
anyhow = "1.0.91"
pest = "2.7.14"
pest_derive = "2.7.14"
